# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 401, 271))
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuMultiple_Cam = QtWidgets.QMenu(self.menuView)
        self.menuMultiple_Cam.setObjectName("menuMultiple_Cam")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Camera = QtWidgets.QAction(MainWindow)
        self.actionNew_Camera.setObjectName("actionNew_Camera")
        self.actionImport_List = QtWidgets.QAction(MainWindow)
        self.actionImport_List.setObjectName("actionImport_List")
        self.actionSingle_Cam = QtWidgets.QAction(MainWindow)
        self.actionSingle_Cam.setObjectName("actionSingle_Cam")
        self.actionAuto_Switch = QtWidgets.QAction(MainWindow)
        self.actionAuto_Switch.setObjectName("actionAuto_Switch")
        self.action2_by_2 = QtWidgets.QAction(MainWindow)
        self.action2_by_2.setObjectName("action2_by_2")
        self.action3_by_3 = QtWidgets.QAction(MainWindow)
        self.action3_by_3.setObjectName("action3_by_3")
        self.action4_by_4 = QtWidgets.QAction(MainWindow)
        self.action4_by_4.setObjectName("action4_by_4")
        self.menuFile.addAction(self.actionNew_Camera)
        self.menuFile.addAction(self.actionImport_List)
        self.menuMultiple_Cam.addAction(self.action2_by_2)
        self.menuMultiple_Cam.addAction(self.action3_by_3)
        self.menuMultiple_Cam.addAction(self.action4_by_4)
        self.menuView.addAction(self.actionSingle_Cam)
        self.menuView.addAction(self.actionAuto_Switch)
        self.menuView.addAction(self.menuMultiple_Cam.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuMultiple_Cam.setTitle(_translate("MainWindow", "Multiple Cam"))
        self.actionNew_Camera.setText(_translate("MainWindow", "New Camera"))
        self.actionImport_List.setText(_translate("MainWindow", "Import List"))
        self.actionSingle_Cam.setText(_translate("MainWindow", "Single Cam"))
        self.actionAuto_Switch.setText(_translate("MainWindow", "Auto Switch"))
        self.action2_by_2.setText(_translate("MainWindow", "2 by 2"))
        self.action3_by_3.setText(_translate("MainWindow", "3 by 3"))
        self.action4_by_4.setText(_translate("MainWindow", "4 by 4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
